version: "3.9"
services:
  # Nodejs App 
  nodejs:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
  # nginx
  nginx:
    depends_on:
      - "nodejs"
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
    restart: always