version: "3.9"
services:
  # Nodejs App 
  app:
    container_name: "server-dairy-ext-nodejs"
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
  # nginx
  nginx:
    container_name: "server-dairy-ext-nginx"
    depends_on:
      - "app"
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/static
    restart: always