version: "3.9"
services:
  # Nodejs App 
  app:
    container_name: "server-dairy-ext-nodejs"
    build: .
    ports:
      - "5500:5500"
    volumes:
      - .:/usr/src/app
  # nginx
  nginx:
    container_name: "server-dairy-ext-nginx"
    depends_on:
      - "app"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/
      - ./static/:/var/www/static/
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    restart: always
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/